import { Metadata } from "next"
import Link from "next/link"


export const metadata:Metadata = {
	title: {
		default: 'Next Js Series by Viswah',
		template: '%s | The Everything App'
	},
	description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: 'gray',
            padding: '1rem',
			display: 'flex',
			gap: '2rem'
          }}
        >
			<Link href='/blog'>Blog</Link>
			<Link href='/dashboard'>Dashboard</Link>
			<Link href='/homes'>Listings</Link>
			<Link href='/services'>Services</Link>
			<Link href={'/'}>Home</Link>
          <h1 style={{ fontSize:'1rem', margin: 'auto'}}>Header</h1>
        </header>
        {children}
        <footer style={{
          backgroundColor: 'gray',
          padding: '1rem'
        }}>
          <h6 style={{margin: 'auto'}}>Footer</h6>
        </footer>
      </body>
    </html>
  )
}
