export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: 'gray',
            padding: '1rem',
          }}
        >
          <h1 style={{ fontSize:'1rem', margin: 'auto'}}>Header</h1>
        </header>
        {children}
        <footer style={{
          backgroundColor: 'gray',
          padding: '1rem'
        }}>
          <h6 style={{margin: 'auto'}}>Footer</h6>
        </footer>
      </body>
    </html>
  )
}
